### ISSUE TITLE
OBJ模型

### ISSUE THREAD

**Issue by xuyilong** [Iridescent-Xuan/loft-opengl#1]
老哥你好，我下载了你的代码想运行试试，发现没有Bedroom.obj，这个是您不想放出来吗？如果您愿意帮助我，那我就求一下OBJ文件中的模型和材质，如果可以的话麻烦发给xuyilong0803@foxmail.com。十分感谢！

**Comment by Iridescent-Xuan** [comment]
同学，

你好！




谢谢你的提醒，不知道为什么，我忘记上传了。

但是大作业什么的还是自己写比较好吧:)


-----原始邮件-----
发件人:DITSpring ***@***.***>
发送时间:2023-04-18 11:39:39 (星期二)
收件人: Iridescent-Xuan/loft-opengl ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Iridescent-Xuan/loft-opengl] OBJ模型 (Issue #1)






***@***.***。十分感谢！
